// #region update price product
export const UPDATE_PRICE_REQUEST = 'UPDATE_PRICE_REQUEST'
export const UPDATE_PRICE_SUCCESS = 'UPDATE_PRICE_SUCCESS'
export const UPDATE_PRICE_FAILURE = 'UPDATE_PRICE_FAILURE'
// #endregion

// #region get all price product
export const GET_ALL_UPDATE_PRICE_REQUEST = 'GET_ALL_UPDATE_PRICE_REQUEST'
export const GET_ALL_UPDATE_PRICE_SUCCESS = 'GET_ALL_UPDATE_PRICE_SUCCESS'
export const GET_ALL_UPDATE_PRICE_FAILURE = 'GET_ALL_UPDATE_PRICE_FAILURE'
// #endregion

// #region get price by product id
export const GET_PRICE_BY_PRODUCT_ID_REQUEST = 'GET_PRICE_BY_PRODUCT_ID_REQUEST'
export const GET_PRICE_BY_PRODUCT_ID_SUCCESS = 'GET_PRICE_BY_PRODUCT_ID_SUCCESS'
export const GET_PRICE_BY_PRODUCT_ID_FAILURE = 'GET_PRICE_BY_PRODUCT_ID_FAILURE'
// #endregion
