export const FETCH_NEWS = 'FETCH_NEWS'
export const SET_NEWS = 'SET_NEWS'

export const GET_ALL_COUPONS_REQUEST = 'GET_ALL_COUPONS_REQUEST'
export const GET_ALL_COUPONS_SUCCESS = 'GET_ALL_COUPONS_SUCCESS'
export const GET_ALL_COUPONS_FAILURE = 'GET_ALL_COUPONS_FAILURE'

export const GET_ALL_COUPON_DETAIL_REQUEST = 'GET_ALL_COUPON_DETAIL_REQUEST'
export const GET_ALL_COUPON_DETAIL_SUCCESS = 'GET_ALL_COUPON_DETAIL_SUCCESS'
export const GET_ALL_COUPON_DETAIL_FAILURE = 'GET_ALL_COUPON_DETAIL_FAILURE'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE'

export const GET_ALL_CART_REQUEST = 'GET_ALL_CART_REQUEST'
export const GET_ALL_CART_SUCCESS = 'GET_ALL_CART_SUCCESS'
export const GET_ALL_CART_FAILURE = 'GET_ALL_CART_FAILURE'

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE'

export const GET_ALL_ROLE_REQUEST = 'GET_ALL_ROLE_REQUEST'
export const GET_ALL_ROLE_SUCCESS = 'GET_ALL_ROLE_SUCCESS'
export const GET_ALL_ROLE_FAILURE = 'GET_ALL_ROLE_FAILURE'

export const GET_ALL_PRODUCTS_CUSTOMER_REQUEST =
  'GET_ALL_PRODUCTS_CUSTOMER_REQUEST'
export const GET_ALL_PRODUCTS_CUSTOMER_SUCCESS =
  'GET_ALL_PRODUCTS_CUSTOMER_SUCCESS'
export const GET_ALL_PRODUCTS_CUSTOMER_FAILURE =
  'GET_ALL_PRODUCTS_CUSTOMER_FAILURE'

export const RESET_ADD_ORDER_STATE = 'RESET_ADD_ORDER_STATE'
export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE'

export const RESET_ADD_CART_STATE = 'RESET_ADD_CART_STATE'
export const ADD_CART_REQUEST = 'ADD_CART_REQUEST'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE'

export const RESET_ADD_COUPON_STATE = 'RESET_ADD_COUPON_STATE'
export const ADD_COUPON_REQUEST = 'ADD_COUPON_REQUEST'
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS'
export const ADD_COUPON_FAILURE = 'ADD_COUPON_FAILURE'

export const RESET_ADD_PRODUCT_STATE = 'RESET_ADD_PRODUCT_STATE'
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'
export const ADD_PRODUCT_REQUEST_BATCH = 'ADD_PRODUCT_REQUEST_BATCH'
export const ADD_PRODUCT_SUCCESS_BATCH = 'ADD_PRODUCT_SUCCESS_BATCH'
export const ADD_PRODUCT_FAILURE_BATCH = 'ADD_PRODUCT_FAILURE_BATCH'
export const RESET_UPDATE_PRODUCT_STATE = 'RESET_UPDATE_PRODUCT_STATE'
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST'
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'
export const GET_PRODUCT_DETAIL_FAILURE = 'GET_PRODUCT_DETAIL_FAILURE'

export const GET_CUSTOMER_ORDERS_REQUEST = 'GET_CUSTOMER_ORDERS_REQUEST'
export const GET_CUSTOMER_ORDERS_SUCCESS = 'GET_CUSTOMER_ORDERS_SUCCESS'
export const GET_CUSTOMER_ORDERS_FAILURE = 'GET_CUSTOMER_ORDERS_FAILURE'

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE'

export const GET_ALL_REVIEW_CUSTOMER_REQUEST = 'GET_ALL_REVIEW_CUSTOMER_REQUEST'
export const GET_ALL_REVIEW_CUSTOMER_SUCCESS = 'GET_ALL_REVIEW_CUSTOMER_SUCCESS'
export const GET_ALL_REVIEW_CUSTOMER_FAILURE = 'GET_ALL_REVIEW_CUSTOMER_FAILURE'

export const GET_ALL_REVIEW_PRODUCT_REQUEST = 'GET_ALL_REVIEW_PRODUCT_REQUEST'
export const GET_ALL_REVIEW_PRODUCT_SUCCESS = 'GET_ALL_REVIEW_PRODUCT_SUCCESS'
export const GET_ALL_REVIEW_PRODUCT_FAILURE = 'GET_ALL_REVIEW_PRODUCT_FAILURE'

export const GET_ORDER_DETAIL_REQUEST = 'GET_ORDER_DETAIL_REQUEST'
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS'
export const GET_ORDER_DETAIL_FAILURE = 'GET_ORDER_DETAIL_FAILURE'

export const GET_ALL_CUSTOMERS_REQUEST = 'GET_ALL_CUSTOMERS_REQUEST'
export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS'
export const GET_ALL_CUSTOMERS_FAILURE = 'GET_ALL_CUSTOMERS_FAILURE'

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST'
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS'
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE'

export const GET_ALL_BRAND_REQUEST = 'GET_ALL_BRAND_REQUEST'
export const GET_ALL_BRAND_SUCCESS = 'GET_ALL_BRAND_SUCCESS'
export const GET_ALL_BRAND_FAILURE = 'GET_ALL_BRAND_FAILURE'

export const GET_ALL_STAFFS_REQUEST = 'GET_ALL_STAFFS_REQUEST'
export const GET_ALL_STAFFS_SUCCESS = 'GET_ALL_STAFFS_SUCCESS'
export const GET_ALL_STAFFS_FAILURE = 'GET_ALL_STAFFS_FAILURE'

export const GET_ALL_SUPPLIER_REQUEST = 'GET_ALL_SUPPLIER_REQUEST'
export const GET_ALL_SUPPLIER_SUCCESS = 'GET_ALL_SUPPLIER_SUCCESS'
export const GET_ALL_SUPPLIER_FAILURE = 'GET_ALL_SUPPLIER_FAILURE'

export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST'
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE'

export const GET_ALL_REQUEST_REQUEST = 'GET_ALL_REQUEST_REQUEST'
export const GET_ALL_REQUEST_SUCCESS = 'GET_ALL_REQUEST_SUCCESS'
export const GET_ALL_REQUEST_FAILURE = 'GET_ALL_REQUEST_FAILURE'

export const GET_REQUEST_DETAIL_REQUEST = 'GET_REQUEST_DETAIL_REQUEST'
export const GET_REQUEST_DETAIL_SUCCESS = 'GET_REQUEST_DETAIL_SUCCESS'
export const GET_REQUEST_DETAIL_FAILURE = 'GET_REQUEST_DETAIL_FAILURE'

export const GET_ALL_TRANSACTION_REQUEST = 'GET_ALL_TRANSACTION_REQUEST'
export const GET_ALL_TRANSACTION_SUCCESS = 'GET_ALL_TRANSACTION_SUCCESS'
export const GET_ALL_TRANSACTION_FAILURE = 'GET_ALL_TRANSACTION_FAILURE'

export const GET_TRANSACTION_DETAIL_REQUEST = 'GET_TRANSACTION_DETAIL_REQUEST'
export const GET_TRANSACTION_DETAIL_SUCCESS = 'GET_TRANSACTION_DETAIL_SUCCESS'
export const GET_TRANSACTION_DETAIL_FAILURE = 'GET_TRANSACTION_DETAIL_FAILURE'

export const GET_ALL_TYPE_REQUEST = 'GET_ALL_TYPE_REQUEST'
export const GET_ALL_TYPE_SUCCESS = 'GET_ALL_TYPE_SUCCESS'
export const GET_ALL_TYPE_FAILURE = 'GET_ALL_TYPE_FAILURE'
