export const GET_ALL_ORDER_STATUS_REQUEST = 'GET_ALL_ORDER_STATUS_REQUEST'
export const GET_ALL_ORDER_STATUS_SUCCESS = 'GET_ALL_ORDER_STATUS_SUCCESS'
export const GET_ALL_ORDER_STATUS_FAILURE = 'GET_ALL_ORDER_STATUS_FAILURE'

export const GET_ALL_ORDER_STATUS_CUSTOMER_REQUEST =
  'GET_ALL_ORDER_STATUS_CUSTOMER_REQUEST'
export const GET_ALL_ORDER_STATUS_CUSTOMER_SUCCESS =
  'GET_ALL_ORDER_STATUS_CUSTOMER_SUCCESS'
export const GET_ALL_ORDER_STATUS_CUSTOMER_FAILURE =
  'GET_ALL_ORDER_STATUS_CUSTOMER_FAILURE'
