export const GET_ALL_ORDER_STATUS_REQUEST = 'GET_ALL_ORDER_STATUS_REQUEST'
export const GET_ALL_ORDER_STATUS_SUCCESS = 'GET_ALL_ORDER_STATUS_SUCCESS'
export const GET_ALL_ORDER_STATUS_FAILURE = 'GET_ALL_ORDER_STATUS_FAILURE'
