export const GET_ALL_PRODUCT_COUPON_REQUEST = 'GET_ALL_PRODUCT_COUPON_REQUEST'
export const GET_ALL_PRODUCT_COUPON_SUCCESS = 'GET_ALL_PRODUCT_COUPON_SUCCESS'
export const GET_ALL_PRODUCT_COUPON_FAILURE = 'GET_ALL_PRODUCT_COUPON_FAILURE'
