export const GET_ALL_PRODUCT_COUPON_REQUEST = 'GET_ALL_PRODUCT_COUPON_REQUEST'
export const GET_ALL_PRODUCT_COUPON_SUCCESS = 'GET_ALL_PRODUCT_COUPON_SUCCESS'
export const GET_ALL_PRODUCT_COUPON_FAILURE = 'GET_ALL_PRODUCT_COUPON_FAILURE'

// #region get all product pageable
export const GET_ALL_PRODUCTS_PAGE_REQUEST = 'GET_ALL_PRODUCTS_PAGE_REQUEST'
export const GET_ALL_PRODUCTS_PAGE_SUCCESS = 'GET_ALL_PRODUCTS_PAGE_SUCCESS'
export const GET_ALL_PRODUCTS_PAGE_FAILURE = 'GET_ALL_PRODUCTS_PAGE_FAILURE'
// #endregion

// #region find product by id
export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST'
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE'
// #endregion
