export const UserRole = {
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
  SHIPPER: 'DELIVERY_STAFF',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF',
  WAREHOUSE_KEEPER: 'WAREHOUSE_KEEPER',
  SALESPERSON: 'SALESPERSON',
  BUSINESS_STAFF: 'BUSINESS_STAFF',
  DIRECTOR: 'DIRECTOR',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER'
}
