// #region Get all order customer page
export const GET_ALL_ORDER_CUSTOMER_PAGE_REQUEST =
  'GET_ALL_ORDER_CUSTOMER_PAGE_REQUEST'
export const GET_ALL_ORDER_CUSTOMER_PAGE_SUCCESS =
  'GET_ALL_ORDER_CUSTOMER_PAGE_SUCCESS'
export const GET_ALL_ORDER_CUSTOMER_PAGE_FAILURE =
  'GET_ALL_ORDER_CUSTOMER_PAGE_FAILURE'
// #endregion

// #region Get all order customer page by status
export const GET_ALL_ORDER_STATUS_CUSTOMER_PAGE_REQUEST =
  'GET_ALL_ORDER_STATUS_CUSTOMER_PAGE_REQUEST'
export const GET_ALL_ORDER_STATUS_CUSTOMER_PAGE_SUCCESS =
  'GET_ALL_ORDER_STATUS_CUSTOMER_PAGE_SUCCESS'
export const GET_ALL_ORDER_STATUS_CUSTOMER_PAGE_FAILURE =
  'GET_ALL_ORDER_STATUS_CUSTOMER_PAGE_FAILURE'
// #endregion

// #region Get all order customer page by date
export const SEARCH_ORDER_CUSTOMER_BY_DATE_REQUEST =
  'SEARCH_ORDER_CUSTOMER_BY_DATE_REQUEST'
export const SEARCH_ORDER_CUSTOMER_BY_DATE_SUCCESS =
  'SEARCH_ORDER_CUSTOMER_BY_DATE_SUCCESS'
export const SEARCH_ORDER_CUSTOMER_BY_DATE_FAILURE =
  'SEARCH_ORDER_CUSTOMER_BY_DATE_FAILURE'
// #endregion
