export const GET_STATISTIC_REQUEST = 'GET_STATISTIC_REQUEST'
export const GET_STATISTIC_SUCCESS = 'GET_STATISTIC_SUCCESS'
export const GET_STATISTIC_FAILURE = 'GET_STATISTIC_FAILURE'

// -------------Get quantity product report----------------------
export const GET_QUANTITY_PRODUCT_REPORT_REQUEST =
  'GET_QUANTITY_PRODUCT_REPORT_REQUEST'
export const GET_QUANTITY_PRODUCT_REPORT_SUCCESS =
  'GET_QUANTITY_PRODUCT_REPORT_SUCCESS'
export const GET_QUANTITY_PRODUCT_REPORT_FAILURE =
  'GET_QUANTITY_PRODUCT_REPORT_FAILURE'
// --------------------------------------------------------------
