// #region get all order pageable
export const GET_ALL_ORDER_PAGE_REQUEST = 'GET_ALL_ORDER_PAGE_REQUEST'
export const GET_ALL_ORDER_PAGE_SUCCESS = 'GET_ALL_ORDER_PAGE_SUCCESS'
export const GET_ALL_ORDER_PAGE_FAILURE = 'GET_ALL_ORDER_PAGE_FAILURE'
// #endregion

// #region get all order pageable by status
export const SEARCH_ORDER_BY_STATUS_REQUEST = 'SEARCH_ORDER_BY_STATUS_REQUEST'
export const SEARCH_ORDER_BY_STATUS_SUCCESS = 'SEARCH_ORDER_BY_STATUS_SUCCESS'
export const SEARCH_ORDER_BY_STATUS_FAILURE = 'SEARCH_ORDER_BY_STATUS_FAILURE'
// #endregion

// #region get all order pageable by date
export const SEARCH_ORDER_BY_DATE_REQUEST = 'SEARCH_ORDER_BY_DATE_REQUEST'
export const SEARCH_ORDER_BY_DATE_SUCCESS = 'SEARCH_ORDER_BY_DATE_SUCCESS'
export const SEARCH_ORDER_BY_DATE_FAILURE = 'SEARCH_ORDER_BY_DATE_FAILURE'
// #endregion
